### ISSUE TITLE
Use Boost.Spirit for decoding bytecode

### ISSUE THREAD

**Issue by rightfold** [rightfold/slakken#1]
http://coliru.stacked-crooked.com/a/adf3de78190d3167

**Comment by sehe** [comment]
I'd like to add a diclaimer:

Though I added test cases, I present the code as-is, without any warranty or claim of fitness for any particular pupose :)

**Comment by rightfold** [comment]
Learning curve is too steep, documentation is too bad (Boost), grammar is too trivial.
